# Generated by Django 3.0.3 on 2020-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=128, verbose_name='nome'),
        ),
    ]
