# Generated by Django 3.0 on 2019-12-05 03:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quilombola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
