# Generated by Django 3.0 on 2019-12-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('quilombola', '0002_community_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='area',
            field=models.DecimalField(decimal_places=15, max_digits=19, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='community',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='base.City', verbose_name='city'),
        ),
    ]
