# Generated by Django 3.0 on 2019-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quilombola', '0004_auto_20191229_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='community',
            name='family_no',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='number of families'),
        ),
    ]
