# Generated by Django 3.0.3 on 2020-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quilombola', '0005_auto_20191229_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nome'),
        ),
    ]
