# Generated by Django 3.0.3 on 2020-02-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quilombola', '0006_auto_20200212_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='description'),
        ),
    ]
