# Generated by Django 3.0.3 on 2020-02-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quilombola', '0007_phase_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='quilombola.Phase', verbose_name='phase'),
        ),
    ]
