# Generated by Django 3.0.3 on 2020-02-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quilombola', '0009_remove_phase_phase_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='nome'),
        ),
    ]
